### ISSUE TITLE
"Unstash a group when a tab in the group is loaded" - not working

### ISSUE THREAD

**Issue by pintassilgo** [chzesa/tiled-tab-groups#16]
This pref doesn't seem to be working. Whether checked or not, the group is unstashed when a tab is loaded.

I would like to not unstash when a tab is loaded OR to unstash session-only, so that the group should stash again after restarting the browser. Persistent unstash only by clicking to unstash in the button panel or in groups view.

**Comment by chzesa** [comment]
The configuration wasn't being loaded until a setting was changed, excepting that I can't reproduce the issue.

Switching to a tab in a stashed group always unstash the group, and tab catch currently unstashes the target group. Should there be additional controls for tab catch behaviour?

**Comment by pintassilgo** [comment]
> Switching to a tab in a stashed group always unstash the group

So what this "Unstash a group when a tab in the group is loaded" option do when unchecked? I thought that if it was disabled, stashed group should not be unstashed even if you switch to a tab in this group.

I think of this "stash" feature as for groups of tabs that I rarely access, so that they shoudn't be accessible via hotkeys to next/previous group. Even if there are active tabs in these stashed groups. The only ways to switch to a stashed group should be by TTG screens (button panel and groups view) or by directly selecting a tab from stashed group (like typing "%" in urlbar).

**Comment by chzesa** [comment]
When the option is enabled it will unstash any stashed group whose member is loaded, e.g. by another addon.

Switching to a tab will always unstash the owning group. Firefox doesn't permit hiding the active (currently selected) tab so I elected to disallow the corresponding group to be stashed.

Stashed groups should not, in my opinion, contain active tabs which is why all the tabs are unloaded when their group is stashed.

I will add an option to either unstash, unload the tab, or do nothing on tab catch.

**Comment by chzesa** [comment]
6505370e6773debf64b41d332eb2a93aeae1b931
